//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slash_commands_gui_tool {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("slash_commands_gui_tool.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto save successfully! 的當地語系化字串。
        /// </summary>
        internal static string AutoSaved {
            get {
                return ResourceManager.GetString("AutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Save 的當地語系化字串。
        /// </summary>
        internal static string AutoSync {
            get {
                return ResourceManager.GetString("AutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A slash command is detected on the local side. If there is a duplicate name, the local command will be overwritten! Please click Confirm to continue. 的當地語系化字串。
        /// </summary>
        internal static string BackupNotEmpty {
            get {
                return ResourceManager.GetString("BackupNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have unsaved changes! Selecting another command from the list will discard your modifications.  
        ///Do you want to save your changes before switching? 的當地語系化字串。
        /// </summary>
        internal static string ChangeMsg {
            get {
                return ResourceManager.GetString("ChangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choice Config 的當地語系化字串。
        /// </summary>
        internal static string ChoiceConfig {
            get {
                return ResourceManager.GetString("ChoiceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Client Error! 的當地語系化字串。
        /// </summary>
        internal static string ClientError {
            get {
                return ResourceManager.GetString("ClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please make sure the bot token is valid. 的當地語系化字串。
        /// </summary>
        internal static string ClientErrorMsg {
            get {
                return ResourceManager.GetString("ClientErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The requested client ID does not match. 的當地語系化字串。
        /// </summary>
        internal static string ClientErrorMsg2 {
            get {
                return ResourceManager.GetString("ClientErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connecting... 的當地語系化字串。
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection Successful! 的當地語系化字串。
        /// </summary>
        internal static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy successful 的當地語系化字串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This command has been copied: 的當地語系化字串。
        /// </summary>
        internal static string CopyCmd {
            get {
                return ResourceManager.GetString("CopyCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to reset the database? This will delete all stored client data! 的當地語系化字串。
        /// </summary>
        internal static string DeleDatabase {
            get {
                return ResourceManager.GetString("DeleDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete all local data and exit the program? This will erase all stored clients, saved data, and configuration files! 的當地語系化字串。
        /// </summary>
        internal static string DeletaLocalFile {
            get {
                return ResourceManager.GetString("DeletaLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you absolutely sure you want to delete this? This action is irreversible! Please think carefully before clicking &quot;Confirm.&quot; 的當地語系化字串。
        /// </summary>
        internal static string DeleteLocalFile2 {
            get {
                return ResourceManager.GetString("DeleteLocalFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File error! 的當地語系化字串。
        /// </summary>
        internal static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 json File 的當地語系化字串。
        /// </summary>
        internal static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading client....Complete! 的當地語系化字串。
        /// </summary>
        internal static string LoadClientComplete {
            get {
                return ResourceManager.GetString("LoadClientComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This file does not have any slash commands! 的當地語系化字串。
        /// </summary>
        internal static string LoadFileEmpty {
            get {
                return ResourceManager.GetString("LoadFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reading error form local slash command file! 的當地語系化字串。
        /// </summary>
        internal static string LoadFileError {
            get {
                return ResourceManager.GetString("LoadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Slash Commands from: 的當地語系化字串。
        /// </summary>
        internal static string LoadFrom {
            get {
                return ResourceManager.GetString("LoadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading clients... 的當地語系化字串。
        /// </summary>
        internal static string LoadingClient {
            get {
                return ResourceManager.GetString("LoadingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please wait, Loading all client commands... 的當地語系化字串。
        /// </summary>
        internal static string LoadingCommands {
            get {
                return ResourceManager.GetString("LoadingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Complete! 的當地語系化字串。
        /// </summary>
        internal static string LoadingComplete {
            get {
                return ResourceManager.GetString("LoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Localization Config 的當地語系化字串。
        /// </summary>
        internal static string LocalizationConfig {
            get {
                return ResourceManager.GetString("LocalizationConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Application ID and Client Secret required! 的當地語系化字串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The name cannot be empty or only spaces! 的當地語系化字串。
        /// </summary>
        internal static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name already exists! 的當地語系化字串。
        /// </summary>
        internal static string NameExist {
            get {
                return ResourceManager.GetString("NameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The input contains invalid characters! Only letters,  numbers, and &quot;-&quot;, &quot;_&quot; are allowed. 的當地語系化字串。
        /// </summary>
        internal static string Nameillegal {
            get {
                return ResourceManager.GetString("Nameillegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input contains invalid characters! Only letters, numbers, &quot;-&quot;, &quot;_&quot; and other language characters (such as Chinese, Japanese) are allowed. 的當地語系化字串。
        /// </summary>
        internal static string Nameillegal2 {
            get {
                return ResourceManager.GetString("Nameillegal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The input contains invalid characters! Only numbers is allowed. 的當地語系化字串。
        /// </summary>
        internal static string Nameillegal3 {
            get {
                return ResourceManager.GetString("Nameillegal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Network Error! 的當地語系化字串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check your Internet connection. Make sure you can connect to discord.com 的當地語系化字串。
        /// </summary>
        internal static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open json file 的當地語系化字串。
        /// </summary>
        internal static string OpenJsonFile {
            get {
                return ResourceManager.GetString("OpenJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A duplicate name already exists: 的當地語系化字串。
        /// </summary>
        internal static string PushDuplicate1 {
            get {
                return ResourceManager.GetString("PushDuplicate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to replace this command? 的當地語系化字串。
        /// </summary>
        internal static string PushDuplicate2 {
            get {
                return ResourceManager.GetString("PushDuplicate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No command can be pushed. 的當地語系化字串。
        /// </summary>
        internal static string PushFileEmpty {
            get {
                return ResourceManager.GetString("PushFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please wait, Pushing all command to bot... 的當地語系化字串。
        /// </summary>
        internal static string PushingCommands {
            get {
                return ResourceManager.GetString("PushingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset database success! 的當地語系化字串。
        /// </summary>
        internal static string ResetDone {
            get {
                return ResourceManager.GetString("ResetDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save successfully! 的當地語系化字串。
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save failed! Maybe the data is illegal or the network is disconnected. 的當地語系化字串。
        /// </summary>
        internal static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Failed! 的當地語系化字串。
        /// </summary>
        internal static string SaveFailLocal {
            get {
                return ResourceManager.GetString("SaveFailLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 It has been detected that the current save file has been modified by another application! Please save a new file! 的當地語系化字串。
        /// </summary>
        internal static string SaveHasChanged {
            get {
                return ResourceManager.GetString("SaveHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save json file 的當地語系化字串。
        /// </summary>
        internal static string SaveJsonFile {
            get {
                return ResourceManager.GetString("SaveJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The save is not available. Please click on the local command before using it. 的當地語系化字串。
        /// </summary>
        internal static string SaveLocalUnavailable {
            get {
                return ResourceManager.GetString("SaveLocalUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to overwrite the original file? If you choose No, a new file will be saved. 的當地語系化字串。
        /// </summary>
        internal static string SaveOverwrite {
            get {
                return ResourceManager.GetString("SaveOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Take it easy! You can save again in  的當地語系化字串。
        /// </summary>
        internal static string SlowDown1 {
            get {
                return ResourceManager.GetString("SlowDown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 seconds. 的當地語系化字串。
        /// </summary>
        internal static string SlowDown2 {
            get {
                return ResourceManager.GetString("SlowDown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ← To bot 的當地語系化字串。
        /// </summary>
        internal static string ToBot {
            get {
                return ResourceManager.GetString("ToBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To Local → 的當地語系化字串。
        /// </summary>
        internal static string ToLocal {
            get {
                return ResourceManager.GetString("ToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An unavailable client has been detected! Click Retry to reconnect, or click Confirm to delete this client, otherwise the application will close. 的當地語系化字串。
        /// </summary>
        internal static string VerityClientError {
            get {
                return ResourceManager.GetString("VerityClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to verify database! 的當地語系化字串。
        /// </summary>
        internal static string VerityError {
            get {
                return ResourceManager.GetString("VerityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please click OK to reset the database. 的當地語系化字串。
        /// </summary>
        internal static string VerityError2 {
            get {
                return ResourceManager.GetString("VerityError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Otherwise the application will be closed. 的當地語系化字串。
        /// </summary>
        internal static string VerityError3 {
            get {
                return ResourceManager.GetString("VerityError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning! 的當地語系化字串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exceeding the word limit, please limit to  的當地語系化字串。
        /// </summary>
        internal static string WordLimit1 {
            get {
                return ResourceManager.GetString("WordLimit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 words 的當地語系化字串。
        /// </summary>
        internal static string WordLimit2 {
            get {
                return ResourceManager.GetString("WordLimit2", resourceCulture);
            }
        }
    }
}
